[build]
  command = "npm run build"
  publish = "public"

# 👇 Proxy all /api/* calls to Vercel backend
[[redirects]]
  from = "/api/*"
  to = "https://shahzaib-tts-api.vercel.app/api/:splat"
  status = 200
  force = true
